# -*- coding: utf-8 -*-
"""Churn_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Shqw0ozsMNv4ocb0hAjE4vqA8NIlemF
"""

from google.colab import drive
import pandas as pd
import os

# Mount Google Drive
drive.mount('/content/drive')

# Define the path to your CSV file in Google Drive
file_path = '/content/drive/MyDrive/Colab Notebooks/customer_churn_data.csv'  # Update this path

# Load the CSV file into a pandas DataFrame
df = pd.read_csv(file_path)

# Display the DataFrame
df.head()  # Display the first few rows

"""Descriptive Analysis"""

import matplotlib.pyplot as plt

statistics = {
    'Average': df[['Age', 'ServiceFrequency', 'AverageSpending']].mean(),
    'Median': df[['Age', 'ServiceFrequency', 'AverageSpending']].median(),
    'Standard Deviation': df[['Age', 'ServiceFrequency', 'AverageSpending']].std()
}

# Display the calculated statistics
statistics_df = pd.DataFrame(statistics)
print(statistics_df)

# Plot histograms for the numeric fields
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Plot histogram for Age
axes[0].hist(df['Age'], bins=15, color='skyblue', edgecolor='black')
axes[0].set_title('Age Distribution')
axes[0].set_xlabel('Age')
axes[0].set_ylabel('Frequency')

# Plot histogram for ServiceFrequency
axes[1].hist(df['ServiceFrequency'], bins=15, color='lightgreen', edgecolor='black')
axes[1].set_title('Service Frequency Distribution')
axes[1].set_xlabel('Service Frequency')
axes[1].set_ylabel('Frequency')

# Plot histogram for AverageSpending
axes[2].hist(df['AverageSpending'], bins=15, color='salmon', edgecolor='black')
axes[2].set_title('Average Spending Distribution')
axes[2].set_xlabel('Average Spending')
axes[2].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Assuming you have already loaded your data into the 'df' DataFrame

# Calculate averages, medians, and standard deviations
statistics = {
    'Average': df[['Age', 'ServiceFrequency', 'AverageSpending']].mean(),
    'Median': df[['Age', 'ServiceFrequency', 'AverageSpending']].median(),
    'Standard Deviation': df[['Age', 'ServiceFrequency', 'AverageSpending']].std()
}

# Display the calculated statistics
statistics_df = pd.DataFrame(statistics)
print(statistics_df)

# Plot histograms for the numeric fields (arranged vertically)
fig, axes = plt.subplots(3, 1, figsize=(8, 18))  # 3 rows, 1 column for vertical layout

# Plot histogram for Age
axes[0].hist(df['Age'], bins=15, color='skyblue', edgecolor='black')
axes[0].set_title('Age Distribution')
axes[0].set_xlabel('Age')
axes[0].set_ylabel('Frequency')

# Plot histogram for ServiceFrequency
axes[1].hist(df['ServiceFrequency'], bins=15, color='lightgreen', edgecolor='black')
axes[1].set_title('Service Frequency Distribution')
axes[1].set_xlabel('Service Frequency')
axes[1].set_ylabel('Frequency')

# Plot histogram for AverageSpending
axes[2].hist(df['AverageSpending'], bins=15, color='salmon', edgecolor='black')
axes[2].set_title('Average Spending Distribution')
axes[2].set_xlabel('Average Spending')
axes[2].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

"""Correlation Analysis"""

import seaborn as sns
import matplotlib.pyplot as plt

# Drop non-numeric columns and unnecessary columns
# Exclude 'Region', 'LastActivityDate', 'LastActivityMonth', and 'CustomerID'
numeric_df = df.drop(columns=["CustomerID", "Region", "LastActivityDate", "LastActivityMonth"])

# Calculate the correlation matrix
correlation_matrix = numeric_df.corr()

# Display the correlation matrix
print("Correlation Matrix:")
print(correlation_matrix)

# Visualize the correlation matrix as a heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)
plt.title("Correlation Matrix for Churn Analysis")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Calculate the correlation matrix for the specified numeric variables
correlation_matrix = df[['LastActivityDays', 'SatisfactionScore', 'Churn']].corr()

# Display the correlation matrix
print(correlation_matrix)

# Visualize the correlation matrix using a heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Matrix')
plt.show()

"""Demographic Analysis"""

import pandas as pd
import matplotlib.pyplot as plt

# Assuming you have already loaded your data into the 'df' DataFrame

# 1. Segment Churn by Age Groups
# Define age groups
bins = [18, 30, 40, 50, 60, 70, 80]  # Age group boundaries
labels = ['18-30', '31-40', '41-50', '51-60', '61-70', '71-80']  # Age group labels
df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels, right=False)

# Calculate churn rates by Age Group
age_churn_rate = df.groupby('AgeGroup')['Churn'].value_counts(normalize=True).unstack().fillna(0)
age_churn_rate = age_churn_rate[1]  # Extract churn rate (Churn = 1)

# Remove age groups with 0.0% churn rate
age_churn_rate = age_churn_rate[age_churn_rate > 0]

# 2. Segment Churn by Region
# Calculate churn rates by Region
region_churn_rate = df.groupby('Region')['Churn'].value_counts(normalize=True).unstack().fillna(0)
region_churn_rate = region_churn_rate[1]  # Extract churn rate (Churn = 1)

# 3. Visualize the churn rates using pie charts

# Plot pie chart for churn rates by Age Group
plt.figure(figsize=(12, 6))

# Pie chart for Age Group
plt.subplot(1, 2, 1)
age_churn_rate.plot(kind='pie', autopct='%1.1f%%', startangle=90, colors=['#FF9999', '#66B3FF'])
plt.title('Churn Rate by Age Group')
plt.ylabel('')  # Remove the y-label for better appearance

# Pie chart for Region
plt.subplot(1, 2, 2)
region_churn_rate.plot(kind='pie', autopct='%1.1f%%', startangle=90, colors=['#FFCC99', '#99FF99', '#66CCFF'])
plt.title('Churn Rate by Region')
plt.ylabel('')  # Remove the y-label for better appearance

# Display both pie charts
plt.tight_layout()
plt.show()

"""Behavioral Analysis"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Assuming you have already loaded your data into the 'df' DataFrame

# 1. Calculate summary statistics for churned vs non-churned customers
churned = df[df['Churn'] == 1]
non_churned = df[df['Churn'] == 0]

# Summary statistics for ServiceFrequency, AverageSpending, and LastActivityDays
summary_stats = {
    'ServiceFrequency': {
        'Churned': churned['ServiceFrequency'].describe(),
        'Non-Churned': non_churned['ServiceFrequency'].describe()
    },
    'AverageSpending': {
        'Churned': churned['AverageSpending'].describe(),
        'Non-Churned': non_churned['AverageSpending'].describe()
    },
    'LastActivityDays': {
        'Churned': churned['LastActivityDays'].describe(),
        'Non-Churned': non_churned['LastActivityDays'].describe()
    }
}

# Print summary statistics
for var, stats in summary_stats.items():
    print(f"\n{var} Summary Statistics:")
    print(f"Churned:\n{stats['Churned']}")
    print(f"Non-Churned:\n{stats['Non-Churned']}")

# 2. Visualize the distributions using box plots for better comparison
plt.figure(figsize=(12, 8))

# Box plot for ServiceFrequency
plt.subplot(2, 2, 1)
sns.boxplot(x='Churn', y='ServiceFrequency', data=df, palette='Set2')
plt.title('Service Frequency: Churned vs Non-Churned')

# Box plot for AverageSpending
plt.subplot(2, 2, 2)
sns.boxplot(x='Churn', y='AverageSpending', data=df, palette='Set2')
plt.title('Average Spending: Churned vs Non-Churned')

# Box plot for LastActivityDays
plt.subplot(2, 2, 3)
sns.boxplot(x='Churn', y='LastActivityDays', data=df, palette='Set2')
plt.title('Last Activity Days: Churned vs Non-Churned')

plt.tight_layout()
plt.show()

"""Time based"""

import matplotlib.pyplot as plt
import seaborn as sns

# Convert LastActivityMonth to a datetime type for proper sorting
df['LastActivityMonth'] = pd.to_datetime(df['LastActivityMonth'], format='%Y-%m')

# Aggregate churn data by LastActivityMonth
monthly_churn = df.groupby('LastActivityMonth')['Churn'].mean().reset_index()

# Rename columns for clarity
monthly_churn.columns = ['LastActivityMonth', 'ChurnRate']

# Plot churn rates over time
plt.figure(figsize=(12, 6))
sns.lineplot(data=monthly_churn, x='LastActivityMonth', y='ChurnRate', marker='o', linewidth=2, color='b')
plt.title('Churn Rates Over Time', fontsize=16)
plt.xlabel('Last Activity Month', fontsize=12)
plt.ylabel('Churn Rate', fontsize=12)
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""Satisfaction Score Analysis"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Step 1: Compare average SatisfactionScore for churned vs. non-churned customers
satisfaction_comparison = df.groupby('Churn')['SatisfactionScore'].mean()
print("Average Satisfaction Score Comparison:")
print(satisfaction_comparison)

# Step 2: Segment customers by SatisfactionScore
bins = [0, 3, 6, 10]  # Define bins for Low, Medium, High satisfaction
labels = ['Low', 'Medium', 'High']
df['SatisfactionSegment'] = pd.cut(df['SatisfactionScore'], bins=bins, labels=labels, include_lowest=True)

# Calculate churn rates for each segment
satisfaction_churn_rates = df.groupby('SatisfactionSegment')['Churn'].mean().reset_index()

# Step 3: Visualize the comparison of average satisfaction scores
plt.figure(figsize=(8, 5))
sns.barplot(x=satisfaction_comparison.index, y=satisfaction_comparison.values, palette='viridis')
plt.title('Average Satisfaction Score: Churned vs Non-Churned', fontsize=14)
plt.xlabel('Churn', fontsize=12)
plt.ylabel('Average Satisfaction Score', fontsize=12)
plt.xticks([0, 1], ['Non-Churned', 'Churned'])
plt.ylim(0, 10)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

# Step 4: Visualize churn rates for each satisfaction segment
plt.figure(figsize=(8, 5))
sns.barplot(data=satisfaction_churn_rates, x='SatisfactionSegment', y='Churn', palette='coolwarm')
plt.title('Churn Rates by Satisfaction Segment', fontsize=14)
plt.xlabel('Satisfaction Segment', fontsize=12)
plt.ylabel('Churn Rate', fontsize=12)
plt.ylim(0, 1)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

"""Complaint Analysis"""

# Compare the number of customers who filed complaints vs. those who didn't
complaint_summary = df['Complaints'].apply(lambda x: 'Filed Complaint' if x > 0 else 'No Complaint').value_counts()
print("Complaint Summary:")
print(complaint_summary)

# Calculate churn rates for each group
df['ComplaintStatus'] = df['Complaints'].apply(lambda x: 'Filed Complaint' if x > 0 else 'No Complaint')
churn_by_complaint = df.groupby('ComplaintStatus')['Churn'].mean().reset_index()

# Visualization: Number of customers by complaint status
plt.figure(figsize=(8, 5))
sns.barplot(x=complaint_summary.index, y=complaint_summary.values, palette='pastel')
plt.title('Number of Customers: Filed Complaint vs No Complaint', fontsize=14)
plt.xlabel('Complaint Status', fontsize=12)
plt.ylabel('Number of Customers', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

# Visualization: Churn rates for customers with and without complaints
plt.figure(figsize=(8, 5))
sns.barplot(data=churn_by_complaint, x='ComplaintStatus', y='Churn', palette='coolwarm')
plt.title('Churn Rates: Filed Complaint vs No Complaint', fontsize=14)
plt.xlabel('Complaint Status', fontsize=12)
plt.ylabel('Churn Rate', fontsize=12)
plt.ylim(0, 1)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

"""Loyalty program"""

# Calculate churn rates for customers in and out of the loyalty program
churn_by_loyalty = df.groupby('LoyaltyProgram')['Churn'].mean().reset_index()
churn_by_loyalty['LoyaltyProgram'] = churn_by_loyalty['LoyaltyProgram'].replace({1: 'In Program', 0: 'Not in Program'})

# Visualization: Churn rates by loyalty program status
plt.figure(figsize=(8, 5))
sns.barplot(data=churn_by_loyalty, x='LoyaltyProgram', y='Churn', palette='coolwarm')
plt.title('Churn Rates: Loyalty Program Members vs Non-Members', fontsize=14)
plt.xlabel('Loyalty Program Status', fontsize=12)
plt.ylabel('Churn Rate', fontsize=12)
plt.ylim(0, 1)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

# Calculate average spending and satisfaction scores for both groups
loyalty_comparison = df.groupby('LoyaltyProgram')[['AverageSpending', 'SatisfactionScore']].mean().reset_index()
loyalty_comparison['LoyaltyProgram'] = loyalty_comparison['LoyaltyProgram'].replace({1: 'In Program', 0: 'Not in Program'})

print("Average Spending and Satisfaction Scores for Loyalty Program Members vs Non-Members:")
print(loyalty_comparison)

# Visualization: Spending and Satisfaction Scores
fig, ax = plt.subplots(1, 2, figsize=(16, 5))

# Average Spending
sns.barplot(data=loyalty_comparison, x='LoyaltyProgram', y='AverageSpending', palette='viridis', ax=ax[0])
ax[0].set_title('Average Spending: Loyalty Program', fontsize=14)
ax[0].set_xlabel('Loyalty Program Status', fontsize=12)
ax[0].set_ylabel('Average Spending', fontsize=12)
ax[0].grid(axis='y', linestyle='--', alpha=0.6)

# Satisfaction Score
sns.barplot(data=loyalty_comparison, x='LoyaltyProgram', y='SatisfactionScore', palette='magma', ax=ax[1])
ax[1].set_title('Satisfaction Scores: Loyalty Program', fontsize=14)
ax[1].set_xlabel('Loyalty Program Status', fontsize=12)
ax[1].set_ylabel('Satisfaction Score', fontsize=12)
ax[1].grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Step 1: Analyze trends in AverageSpending and SubscriptionLength
# Group data by SubscriptionLength (bucketed into categories if needed for clarity)
df['SubscriptionBucket'] = pd.cut(df['SubscriptionLength'], bins=[0, 6, 12, 24, 36, df['SubscriptionLength'].max()],
                                  labels=['0-6 months', '6-12 months', '1-2 years', '2-3 years', '3+ years'])

# Calculate average spending and satisfaction per subscription bucket
trends = df.groupby('SubscriptionBucket')[['AverageSpending', 'SatisfactionScore']].mean().reset_index()

# Step 2: Visualization
fig, ax = plt.subplots(2, 1, figsize=(10, 10), sharex=True)

# Average Spending vs Subscription Length
sns.lineplot(data=trends, x='SubscriptionBucket', y='AverageSpending', marker='o', ax=ax[0], color='teal')
ax[0].set_title('Average Spending Over Subscription Length', fontsize=14)
ax[0].set_xlabel('Subscription Length', fontsize=12)
ax[0].set_ylabel('Average Spending', fontsize=12)
ax[0].grid(axis='y', linestyle='--', alpha=0.6)

# Satisfaction Score vs Subscription Length
sns.lineplot(data=trends, x='SubscriptionBucket', y='SatisfactionScore', marker='o', ax=ax[1], color='darkorange')
ax[1].set_title('Satisfaction Score Over Subscription Length', fontsize=14)
ax[1].set_xlabel('Subscription Length', fontsize=12)
ax[1].set_ylabel('Satisfaction Score', fontsize=12)
ax[1].grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

"""Customer in rural area with low satisfaction score"""

# Step 1: Filter customers in the "Rural" region with low satisfaction
low_satisfaction_threshold = 4  # Define threshold for low satisfaction
rural_low_satisfaction = df[(df['Region'] == 'Rural') & (df['SatisfactionScore'] < low_satisfaction_threshold)]

# Display the filtered data
print("Customers in the 'Rural' Region with Low Satisfaction:")
print(rural_low_satisfaction)

# Step 2: Visualization: Satisfaction score distribution for Rural region
plt.figure(figsize=(8, 6))
sns.histplot(df[df['Region'] == 'Rural']['SatisfactionScore'], bins=10, kde=True, color='skyblue', alpha=0.7)
plt.axvline(low_satisfaction_threshold, color='red', linestyle='--', label='Low Satisfaction Threshold')
plt.title('Satisfaction Score Distribution: Rural Region', fontsize=14)
plt.xlabel('Satisfaction Score', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

# Step 3: Count of customers with low satisfaction in Rural region
low_satisfaction_count = rural_low_satisfaction.shape[0]
print(f"Number of customers in the 'Rural' region with low satisfaction: {low_satisfaction_count}")

"""XGBoost"""

df.head(10)

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
import xgboost as xgb
import matplotlib.pyplot as plt

# Features and Target
predictors = ['Age', 'ServiceFrequency', 'SatisfactionScore', 'LastActivityDays', 'LoyaltyProgram', 'Complaints']
target = 'Churn'

# Ensure there are no missing values
df = df.dropna(subset=predictors + [target])

# Split into features (X) and target (y)
X = df[predictors]
y = df[target]

# Train-test split (70-30)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Convert data into DMatrix for XGBoost
train_data = xgb.DMatrix(X_train, label=y_train)
test_data = xgb.DMatrix(X_test, label=y_test)

# XGBoost parameters
params = {
    'objective': 'binary:logistic',  # Binary classification
    'eval_metric': 'logloss',       # Logarithmic loss
    'eta': 0.1,                     # Learning rate
    'max_depth': 6,                 # Tree depth
    'subsample': 0.8,               # Subsample ratio
    'colsample_bytree': 0.8,        # Column subsample ratio
    'seed': 42                      # Random seed
}

# Train the XGBoost model
bst = xgb.train(params, train_data, num_boost_round=100)

# Make predictions
y_pred_proba = bst.predict(test_data)
y_pred = (y_pred_proba > 0.5).astype(int)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

# Print results
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Feature Importance Plot
xgb.plot_importance(bst, importance_type='weight', title='Feature Importance (Weight)', show_values=True)
plt.tight_layout()
plt.show()